apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: influxdb
  labels:
    server: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
     server: influxdb
  template:
    metadata:
      labels:
        server: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb:1.4.3-alpine
        env:
        - name: INFLUXDB_DB
          value: "monitoring"
        - name: INFLUXDB_HTTP_AUTH_ENABLED
          value: "true"
        - name: INFLUXDB_ADMIN_USER
          value: "admin"
        - name: INFLUXDB_ADMIN_PASSWORD
          value: "admin"
        - name: INFLUXDB_REPORTING_DISABLED
          value: "true"
        - name: INFLUXDB_ADMIN_ENABLED
          value: "true"
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 8083
          name: http-ui
        - containerPort: 8086
          name: http-api
        - containerPort: 8088
          name: rpc
