apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-persistent-storage
  labels:
    app: influxdb-persistent-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
