apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    server: influxdb
spec:
  type: NodePort
  selector:
    server: influxdb
  ports:
  - name: http-ui
    port: 8083
  - name: http-api
    port: 8086
  - name: rpc
    port: 8088
